new -t [tag_0]
new -t [tag_1]
new -t [tag_2]
new -t [tag_3]
new -t [tag_4]
new -t [tag_5]
new -t [tag_6]
new -t [tag_7]
new -t [tag_8]
new -t [tag_9]
new /tag_6/tag_2/tag_1/tag_3/tag_7/file_0
new /tag_3/tag_9/tag_2/file_1
new /tag_3/tag_5/tag_6/tag_8/tag_0/tag_1/tag_2/tag_9/tag_7/tag_4/file_2
new /tag_3/tag_5/tag_0/tag_7/tag_1/tag_4/tag_8/tag_6/file_3
new /tag_7/tag_6/tag_5/tag_1/tag_8/tag_2/file_4
new /tag_7/tag_1/tag_4/tag_6/tag_9/tag_5/tag_8/tag_2/file_5
new /tag_2/tag_1/tag_9/tag_0/tag_3/tag_6/tag_7/tag_5/tag_4/file_6
new /tag_0/tag_9/tag_5/tag_6/tag_1/tag_4/tag_7/tag_3/tag_8/file_7
new /tag_8/tag_1/tag_6/tag_9/tag_5/tag_7/tag_4/tag_2/tag_0/file_8
new /tag_2/tag_0/tag_7/tag_6/tag_8/tag_9/tag_4/file_9
new /tag_9/tag_2/tag_0/tag_4/tag_6/tag_8/tag_1/tag_5/file_10
new /tag_4/tag_3/tag_2/tag_6/tag_7/tag_8/tag_0/tag_1/tag_5/file_10
new /tag_9/tag_1/tag_6/tag_7/tag_4/tag_8/tag_3/tag_5/file_10
new /tag_9/tag_5/tag_2/tag_0/tag_1/tag_4/tag_6/tag_7/file_10
new /tag_8/tag_4/tag_2/tag_5/tag_1/tag_7/tag_3/tag_0/file_10
new /tag_4/tag_3/tag_1/tag_9/tag_7/tag_8/tag_6/tag_2/file_11
new /tag_5/tag_6/tag_4/tag_3/tag_2/tag_8/tag_1/tag_0/file_12
new /tag_0/tag_5/tag_3/tag_4/tag_1/tag_9/tag_6/file_13
new /tag_8/tag_4/tag_9/tag_0/tag_7/tag_5/tag_6/tag_2/tag_1/tag_3/file_13
new /tag_9/tag_3/tag_0/tag_4/tag_7/tag_8/tag_2/tag_5/file_14
new /tag_4/tag_8/tag_5/tag_1/tag_2/tag_7/tag_6/tag_9/tag_3/tag_0/file_15
new /tag_0/tag_4/tag_9/tag_6/tag_8/tag_1/tag_5/tag_3/tag_2/tag_7/file_16
new /tag_6/tag_1/tag_4/tag_0/tag_3/tag_7/tag_5/file_17
new /tag_3/tag_0/tag_6/tag_8/tag_4/tag_1/tag_5/tag_2/tag_7/tag_9/file_18
new /tag_5/tag_8/tag_4/tag_7/tag_6/tag_3/tag_2/tag_9/tag_0/tag_1/file_19
end